#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# fpga_host_test.tcl: Tcl script for re-creating project 'fpga_host_test'
#
# Generated by Vivado on Sun Mar 14 15:19:38 -0700 2021
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#

set blackparrot_dir "."
set arty_dir "."

# Check file required for this script exists
proc checkRequiredFiles { blackparrot_dir arty_dir } {
  set status true
  set files [list \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_defines.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_wormhole_router.vh" \
   "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_noc_links.vh" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_wormhole_defines.svh" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_cce_defines.svh" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_defines.svh" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_defines.svh" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_pkgdef.svh" \
   "${arty_dir}/src/include/bp_fpga_host_pkgdef.svh" \
   "${arty_dir}/src/include/bp_fpga_host_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_instr_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_csr_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_log_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_core_if.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_if.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_addr_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_if.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_core_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_defines.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_addr_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_pkgdef.svh" \
   "${blackparrot_dir}/bp_common/src/include/bp_common_pkg.sv" \
   "${blackparrot_dir}/bp_me/src/include/bp_me_pkg.sv" \
   "${arty_dir}/src/include/bp_fpga_host_pkg.sv" \
   "${arty_dir}/src/v/bp_fpga_host.sv" \
   "${arty_dir}/src/v/bp_fpga_host_io_in.sv" \
   "${arty_dir}/src/v/bp_fpga_host_io_out.sv" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_array_reverse.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_circular_ptr.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_clkgate_optional.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_clear_up_one_hot.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_up_down.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dff_en.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dlatch.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_hardened.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_tracker.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_flow_counter.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync_synth.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_synth.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_mux_one_hot.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_parallel_in_serial_out_passthrough.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_serial_in_parallel_out_passthrough.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_two_fifo.v" \
   "${arty_dir}/src/v/uart_rx.sv" \
   "${arty_dir}/src/v/uart_tx.sv" \
   "${arty_dir}/src/test/fpga_host_system.sv" \
   "${arty_dir}/src/fpga-test/xdc/constraints.xdc" \
   "${arty_dir}/src/test/fpga_host_testbench.sv" \
   "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_reset_gen.v" \
   "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_clock_gen.v" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "fpga_host_test"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "fpga_host_test.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--blackparrot_dir <path>\]"
  puts "$script_file -tclargs \[--arty_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--blackparrot_dir"   { incr i; set blackparrot_dir [lindex $::argv $i] }
      "--arty_dir"   { incr i; set arty_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $blackparrot_dir $arty_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:arty-a7-100:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "arty-a7-100" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "48" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_defines.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_wormhole_router.vh"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_noc_links.vh"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_wormhole_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_cce_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_pkgdef.svh"] \
 [file normalize "${arty_dir}/src/include/bp_fpga_host_pkgdef.svh"] \
 [file normalize "${arty_dir}/src/include/bp_fpga_host_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_instr_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_csr_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_log_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_core_if.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_if.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_addr_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_if.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_core_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_defines.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_addr_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_pkgdef.svh"] \
 [file normalize "${blackparrot_dir}/bp_common/src/include/bp_common_pkg.sv"] \
 [file normalize "${blackparrot_dir}/bp_me/src/include/bp_me_pkg.sv"] \
 [file normalize "${arty_dir}/src/include/bp_fpga_host_pkg.sv"] \
 [file normalize "${arty_dir}/src/v/bp_fpga_host.sv"] \
 [file normalize "${arty_dir}/src/v/bp_fpga_host_io_in.sv"] \
 [file normalize "${arty_dir}/src/v/bp_fpga_host_io_out.sv"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_array_reverse.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_circular_ptr.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_clkgate_optional.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_clear_up_one_hot.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_up_down.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dff_en.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dlatch.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_hardened.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_tracker.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_flow_counter.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync_synth.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_synth.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_mux_one_hot.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_parallel_in_serial_out_passthrough.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_serial_in_parallel_out_passthrough.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_two_fifo.v"] \
 [file normalize "${arty_dir}/src/v/uart_rx.sv"] \
 [file normalize "${arty_dir}/src/v/uart_tx.sv"] \
 [file normalize "${arty_dir}/src/test/fpga_host_system.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_wormhole_router.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_noc/bsg_noc_links.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_wormhole_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_cce_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_cce_inst_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${arty_dir}/src/include/bp_fpga_host_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${arty_dir}/src/include/bp_fpga_host_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_instr_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_rv64_csr_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_log_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_core_if.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_if.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_addr_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_if.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_core_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_cfg_bus_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_cache_engine_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_bedrock_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_defines.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_addr_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_aviary_pkgdef.svh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "${blackparrot_dir}/bp_common/src/include/bp_common_pkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/bp_me/src/include/bp_me_pkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/include/bp_fpga_host_pkg.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/v/bp_fpga_host.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/v/bp_fpga_host_io_in.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/v/bp_fpga_host_io_out.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_array_reverse.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_circular_ptr.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_clkgate_optional.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_clear_up_one_hot.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_counter_up_down.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dff_en.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_dlatch.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_hardened.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_fifo_tracker.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_flow_counter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_sync_synth.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_mem/bsg_mem_1r1w_synth.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_misc/bsg_mux_one_hot.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_parallel_in_serial_out_passthrough.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_serial_in_parallel_out_passthrough.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_dataflow/bsg_two_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/v/uart_rx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/v/uart_tx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${arty_dir}/src/test/fpga_host_system.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "fpga_host_system" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${arty_dir}/src/fpga-host/xdc/constraints.xdc]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "${arty_dir}/src/fpga-host/xdc/constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${arty_dir}/src/test/fpga_host_testbench.sv"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_reset_gen.v"] \
 [file normalize "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_clock_gen.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "${arty_dir}/src/test/fpga_host_testbench.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_implementation" -value "0" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_reset_gen.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "${blackparrot_dir}/external/basejump_stl/bsg_test/bsg_nonsynth_clock_gen.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "fpga_host_testbench" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
